basePath: /api/v1
definitions:
  requests.ChangePasswordRequest:
    properties:
      newPassword:
        minLength: 6
        type: string
      oldPassword:
        minLength: 6
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  requests.UserRegistrationRequest:
    properties:
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - name
    - password
    type: object
  requests.UserRequest:
    properties:
      imageId:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
  resources.AuthDto:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/resources.UserDto'
    type: object
  resources.ImageDto:
    properties:
      id:
        type: integer
      link:
        type: string
    type: object
  resources.UserDto:
    properties:
      id:
        type: integer
      image:
        $ref: '#/definitions/resources.ImageDto'
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for nix_chat application.
  title: nix_chat API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: log in user
      parameters:
      - description: User body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requests.UserRegistrationRequest'
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resources.AuthDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Log in user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: User body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requests.UserRegistrationRequest'
      produces:
      - application/json
      - text/xml
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resources.AuthDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new user
      tags:
      - auth
  /users/{id}:
    get:
      consumes:
      - application/json
      description: get user by name
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resources.UserDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Show a user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: change login for user google acc
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requests.UserRequest'
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resources.UserDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Change login for user google acc
      tags:
      - users
  /users/{id}/change-pwd:
    put:
      consumes:
      - application/json
      description: change password for user google acc
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requests.ChangePasswordRequest'
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resources.UserDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Change password for user google acc
      tags:
      - users
  /users/{userId}/image:
    post:
      consumes:
      - image/png
      description: load a new image
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: The file to upload
        in: formData
        name: formData
        required: true
        type: file
      produces:
      - application/json
      - text/xml
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resources.ImageDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Add a new image
      tags:
      - images
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
