version: '3.9'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6364:6379"

  mysqldb:
    image: mysql:8.0
    container_name: nix_chat_db
    environment:
      - MYSQL_USER=${DB_USER:-mysql}
      - MYSQL_PASSWORD=${DB_PASSWORD:-mysql}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=1
      #- MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=${DB_NAME:-nix_chat}
      - DATABASE_HOST=${DB_HOST:-localhost}
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - default

  app:
    container_name: nix_chat
    environment:
      - DB_NAME=${DB_NAME:-nix_chat}
      - DB_HOST=${DB_HOST:-mysqldb}
      - DB_USER=${DB_USER:-mysql}
      - DB_PASSWORD=${DB_PASSWORD:-mysql}
      - JWT_SECRET=${JWT_SECRET:-123456}
      - FILES_LOCATION=${FILES_LOCATION:-/app/file_storage}
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - ../backend/file_storage:/app/file_storage
    ports:
      - '8081:8080'
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - default

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
    depends_on:
      - app

  web:
    build: ../nginx
    volumes:
      - ../backend/file_storage:/var/www/app/file_storage
#      - ../backend/file_storage/89f15875-0e37-4c37-b799-cebc64783466.png:/var/www/app/file_storage/89f15875-0e37-4c37-b799-cebc64783466.png
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  my-db:

networks:
  default:
    driver: bridge