version: '3.9'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6364:6379"
  app:
    container_name: nix_chat
    environment:
      - DB_NAME=${DB_NAME:-nix_chat}
      - DB_HOST=${DB_HOST:-mysqldb}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - JWT_SECRET=${JWT_SECRET:-123456}
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - '8081:8080'
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - default

  mysqldb:
    image: mysql:8.0
    container_name: nix_chat_db
    environment:
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_ROOT_PASSWORD='root'
      - MYSQL_DB=${DB_NAME:-nix_chat}
      - DATABASE_HOST=${DB_HOST:-localhost}
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - default

volumes:
  my-db:

networks:
  default:
    driver: bridge